# If not set, defaults to the directory name of `source_path`
name: 'Odaikun'

# Path is relative to the location of the configuration file and specifies
# the root to expand all paths from
# If not set, defaults to a git repository root
root: '.'

# Path is relative to configuration root and specifies where cached metadata will be stored.
# If not set, defaults to '.licenses'
cache_path: './cache'

# Path is relative to configuration root and specifies the working directory when enumerating dependencies
# Optional for single app configuration, required when specifying multiple apps
# Defaults to current directory when running `licensed`
apps:
  - source_path: './backend'
  - source_path: './frontend'

# Sources of metadata
sources:
  yarn: true
  pipenv: true

yarn:
  production_only: false

# Dependencies with these licenses are allowed and will not raise errors or warnings.
# This list does not have a default value and is required for `licensed status`
# to succeed.
allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense
  - 0bsd
  - wtfpl
  - mpl-2.0

# These dependencies are ignored during enumeration.
# They will not be cached, and will not raise errors or warnings.
# This configuration is intended to be used for dependencies that don't need to
# be included for compliance purposes, such as other projects owned by the current
# project's owner, internal dependencies, and dependencies that aren't shipped with
# the project like test frameworks.
ignored:
  pipenv:
    - chardet
    - click-didyoumean
    - click-repl
    - ipython-genutils
    - pickleshare
    - python-editor
  yarn:
    - aria-query-4.2.2
    - bindings
    - cacache-12.0.4
    - cacache-13.0.1
    - color-convert-1.9.3
    - color-convert-2.0.1
    - css-select-1.2.0
    - doctrine-1.5.0
    - doctrine-2.1.0
    - doctrine-3.0.0
    - eslint-plugin-flowtype-4.6.0
    - eslint-plugin-flowtype-4.7.0
    - faye-websocket-0.11.3
    - harmony-reflect
    - ignore-4.0.6
    - ignore-5.1.8
    - json-schema
    - jsonify
    - qs-6.5.2
    - qs-6.7.0
    - readable-stream-2.3.7
    - readable-stream-3.6.0
    - readdirp-2.2.1
    - source-map-0.5.7
    - source-map-0.6.1
    - spdx-exceptions
    - ssri-6.0.1
    - ssri-7.1.0
    - string_decoder-1.1.1
    - string_decoder-1.3.0
    - websocket-driver-0.7.4
    - file-uri-to-path
    - fsevents-1.2.13
    - fsevents-2.1.2
    - fsevents-2.1.3
    - nan

# These dependencies have licenses not on the `allowed` list and have been reviewed.
# They will be cached and checked, but will not raise errors or warnings for a
# non-allowed license.  Dependencies on this list will still raise errors if
# license text cannot be found for the dependency.
reviewed:
  pipenv:
    - amqp
    - billiard
    - celery
    - certifi
    - cffi
    - click-didyoumean
    - click-repl
    - cryptography
    - idna
    - ipython-genutils
    - itsdangerous
    - jedi
    - kombu
    - packaging
    - parso
    - passlib
    - pexpect
    - pickleshare
    - psycopg2
    - ptyprocess
    - pycparser
    - python-dateutil
    - python-editor
    - python-multipart
    - requests
    - rfc3986
    - traitlets
    - vine
    - wcwidth
    - wheel
    - SQLAlchemy-Utils
  yarn:
    - \@hapi/address
    - \@hapi/bourne
    - \@hapi/hoek
    - \@hapi/joi
    - \@hapi/topo
    - \@material-ui/icons
    - \@typescript-eslint/parser
    - \@typescript-eslint/typescript-estree
    - \@webassemblyjs/helper-fsm
    - \@webassemblyjs/leb128
    - \@xtuc/ieee754
    - abab
    - aria-query-4.2.2
    - atob
    - bcrypt-pbkdf
    - cacache-12.0.4
    - caniuse-lite
    - case-sensitive-paths-webpack-plugin
    - color-convert-1.9.3
    - color-convert-2.0.1
    - css-mediaquery
    - css-select-1.2.0
    - default-gateway
    - detect-node
    - doctrine-1.5.0
    - doctrine-2.1.0
    - doctrine-3.0.0
    - dom-serializer
    - domain-browser
    - electron-to-chromium
    - escodegen
    - eslint-plugin-flowtype-4.6.0
    - eslint-plugin-flowtype-4.7.0
    - eslint-plugin-promise
    - espree
    - esquery
    - faye-websocket-0.11.3
    - figgy-pudding
    - filesize
    - fs.realpath
    - glob
    - glob-to-regexp
    - harmony-reflect
    - hoist-non-react-statics
    - http-parser-js
    - http-proxy
    - ieee754
    - ignore-4.0.6
    - ignore-5.1.8
    - istanbul-lib-coverage
    - istanbul-lib-instrument
    - istanbul-lib-report
    - istanbul-lib-source-maps
    - istanbul-reports
    - jsbn
    - json-parse-even-better-errors
    - json-schema
    - json3
    - jsonify
    # 要注意
    - language-subtag-registry
    - lodash
    - lodash._reinterpolate
    - lodash.memoize
    - lodash.sortby
    - lodash.template
    - lodash.templatesettings
    - lodash.uniq
    - makeerror
    - neo-async
    - node-forge
    - normalize-package-data
    - pako
    - path-browserify
    - path-is-inside
    - pn
    - portfinder
    - postcss-color-gray
    - postcss-load-config
    - postcss-loader
    - qs-6.5.2
    - qs-6.7.0
    - react-transition-group
    - readable-stream-2.3.7
    - readable-stream-3.6.0
    - readdirp-2.2.1
    - retry
    - sax
    - saxes
    - serialize-javascript
    - sha.js
    - source-map-0.5.7
    - source-map-0.6.1
    - spdx-exceptions
    - sprintf-js
    - ssri-6.0.1
    - ssri-7.1.0
    - string_decoder-1.1.1
    - string_decoder-1.3.0
    - svgo
    - table
    - terser
    - tmpl
    - tty-browserify
    - typedarray
    - uri-js
    - walker
    - webpack
    - webpack-dev-server
    - webpack-log
    - websocket-driver-0.7.4
    - websocket-extensions
    - yargs
  