"""Added topic table

Revision ID: 0a9d132df0a9
Revises: 91979b40eb38
Create Date: 2020-10-12 13:38:06.466069-07:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a9d132df0a9"
down_revision = "91979b40eb38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("picture_url", sa.String(), nullable=True),
        sa.Column("post_date", sa.Date(), nullable=True),
        sa.Column("is_visible", sa.Boolean(), nullable=True),
        sa.Column("is_adopted", sa.Boolean(), nullable=True),
        sa.Column("contributor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contributor_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_topic_id"), "topic", ["id"], unique=False)
    op.create_index(op.f("ix_topic_topic"), "topic", ["topic"], unique=False)
    op.alter_column("user", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.drop_column("user", "address")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "address", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.alter_column("user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_index(op.f("ix_topic_topic"), table_name="topic")
    op.drop_index(op.f("ix_topic_id"), table_name="topic")
    op.drop_table("topic")
    # ### end Alembic commands ###
