name: Build and Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run containers.
        run: |
          docker-compose up -d
          sleep 5
          docker-compose run --rm backend alembic upgrade head
          docker-compose run --rm backend python3 app/initial_data.py
      - name: Check Python syntax.
        run: docker-compose run backend flake8 /app
      - name: Tests for backend.
        run: docker-compose run backend pytest -v
      - name: Check JavaScript/TypeScript syntax.
        run: docker-compose run frontend eslint /app
      - name: Tests for frontend.
        run: docker-compose run frontend test
