name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build containers.
        run: ./scripts/build.sh
      - name: Tests for backend
        run: docker-compose run backend pytest -v
      - name: Tests for frontend
        run: docker-compose run frontend test
