name: Check License by Licensed

on:
  push:
    branches:
      - master
      - main
      - develop

jobs:
  licensed_ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: pip install --upgrade pip && pip install pipenv --no-cache-dir
    - run: pipenv install --system --deploy --dev
    - uses: jonabc/setup-licensed@v1
      with:
        version: 2.x
    - run: npm install
    - id: licensed
      uses: jonabc/licensed-ci@v1
      with:
        github_token: ${{ secrets.TOKEN }}
    - uses: actions/github-script@0.2.0
      if: always() && steps.licensed.outputs.pr_number
      with:
        github_token: ${{ secrets.TOKEN }}
        script: |
          github.issues.createComment({
            ...context.repo,
            issue_number: ${{ steps.licensed.outputs.pr_number }}
            body: 'My custom PR message'
          })